# From:	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: head/libexec/rshd/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=rcmds
PROG=	rshd
MAN=	rshd.8

PACKAGE=rcmds

WARNS?=	3
WFORMAT=0

LIBADD=	util pam

.include <bsd.prog.mk>
