#!/bin/sh

#
# Copyright (c) 2016, Henning Matyschok
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

PATH=/bin:/sbin:/usr/bin:/usr/sbin ; export PATH

#
# Create in-memory partitions 
#
# XXX: I'll generalize this code-section... 
#
mount_mfs -s 1m md /tmp
mount_mfs -s 5m md /var
mount_mfs -s 1m md /etc

# Populate /etc
cp -a /c/etc/ /etc
ln -s /usr/share/misc/termcap /etc

exec /etc/rc2
