#
# Network toolbox.
#

#
# It is still assumed that IPv6 Doman was enables.
#

###################################################################
# Programs from stock /bin
#

###################################################################
# Programs from standard /sbin
#
CRUNCH_PROGS_sbin+=	ifconfig ping ping6 route

##################################################################
# Programs from stock /usr/bin
#
CRUNCH_PROGS_usr.bin+=	netstat

##################################################################
# Programs from stock /usr/sbin
#
CRUNCH_PROGS_usr.sbin+=	arp inetd tcpdump wlandebug

##################################################################
# Library dependencies
#
CRUNCH_LIBS+= -lbsdxml
CRUNCH_LIBS+= -lcrypto
CRUNCH_LIBS+= -lipsec
CRUNCH_LIBS+= -lipx
CRUNCH_LIBS+= -ljail
CRUNCH_LIBS+= -lkvm
CRUNCH_LIBS+= -lm
CRUNCH_LIBS+= -lmd
CRUNCH_LIBS+= -lmemstat
CRUNCH_LIBS+= -lnetgraph
CRUNCH_LIBS+= -lpcap
CRUNCH_LIBS+= -lsbuf
CRUNCH_LIBS+= -lutil
CRUNCH_LIBS+= -lwrap

