# $FreeBSD: head/sys/modules/dtrace/Makefile 289769 2015-10-22 21:28:20Z jhb $

.include "Makefile.inc"

SUBDIR=		dtmalloc	\
		dtnfscl		\
		dtrace		\
		dtraceall	\
		dtrace_test	\
		profile		\
		prototype	\
		sdt		\
		systrace \
		fbt

.include <bsd.subdir.mk>
