#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin ; export PATH

# Create in-memory partitions 
mount_mfs -s 1m md /tmp
mount_mfs -s 1m md /var
mount_mfs -s 1m md /etc

# Populate /etc
cp -a /c/etc/ /etc
ln -s /usr/share/misc/termcap /etc

exec /etc/rc2
