#!/bin/sh

echo "*** Populating /var .."

mkdir -p /var/run/hostapd
mkdir -p /var/log
mkdir -p /var/tmp
mkdir -p /var/db
mkdir -p /var/empty
mkdir -p /var/cron
mkdir -p /var/cron/tabs

echo "*** Loading configuration files .."
cfg_load

ln -s /etc/cfg/dhcpd.conf /etc
ln -s /etc/cfg/group /etc
ln -s /etc/cfg/hostname.arge0 /etc
ln -s /etc/cfg/hostname.arge1 /etc
ln -s /etc/cfg/inetd.conf /etc
ln -s /etc/cfg/ipsec.conf /etc
ln -s /etc/cfg/manifest /etc
ln -s /etc/cfg/master.passwd /etc
ln -s /etc/cfg/myname /etc
ln -s /etc/cfg/passwd /etc
ln -s /etc/cfg/pf.conf /etc
ln -s /etc/cfg/rc.conf /etc
ln -s /etc/cfg/wpa_supplicant.conf /etc

mkdir -p /etc/ppp
ln -s /etc/cfg/ppp.conf /etc/ppp

echo "*** Default password/login databases .."
/usr/sbin/pwd_mkdb /etc/master.passwd
/usr/bin/cap_mkdb /etc/login.conf

echo "*** Starting network .."

. /etc/rc.conf

echo "*** setting up hostname"
/bin/hostname ${system_hostname}

# Bring up loopback
echo "*** bringing up loopback .."
/sbin/ifconfig lo0 inet 127.0.0.1/8 up

# Start network
echo "*** Starting networking "
/etc/rc.d/net start

#
# pf(4) -- smp-pf
#
echo "*** Enable smp-pf"
/sbin/pfctl -ef /etc/pf.conf

#
# dhcpd(8)
#
echo "*** Enable dhcpd"
/usr/sbin/dhcpd -c /etc/dhcpd.conf

echo "*** Done!"

exit 0
