# From:	@(#)Makefile	8.3 (Berkeley) 4/2/94
# $FreeBSD: releng/11.0/usr.bin/passwd/Makefile 298107 2016-04-16 07:45:30Z gjb $

.include <src.opts.mk>

PROG	 = passwd
BINOWN	 = root
BINMODE	 = 4555
PRECIOUSPROG=
LIBADD   = pam

beforeinstall:
.for i in passwd yppasswd
	[ ! -e ${DESTDIR}${BINDIR}/$i ] || \
		chflags noschg ${DESTDIR}${BINDIR}/$i || true
.endfor

.include <bsd.prog.mk>
