# $FreeBSD: head/gnu/usr.bin/cc/Makefile.tgt 268351 2014-07-07 00:27:09Z marcel $

# These assignments duplicate much of the functionality of
# TARGET_ARCH, but there's no easy way to export make functions...

.if defined(TARGET_ARCH)
TARGET_CPUARCH=${MACHINE_CPUARCH:C/mips(n32|64)?(el)?/mips/:C/arm(v6)?(eb|hf)?/arm/:C/powerpc64/powerpc/}
.else
TARGET_CPUARCH=${TARGET_ARCH}
.endif
TARGET_ARCH?=	${TARGET_ARCH}
GCC_CPU=${TARGET_CPUARCH:C/amd64/i386/:C/powerpc/rs6000/:C/sparc64/sparc/}

.if ${TARGET_ARCH} == "armeb" || ${TARGET_ARCH} == "armv6eb" || \
	(${TARGET_CPUARCH} == "mips" && ${TARGET_ARCH:Mmips*el} == "")
TARGET_BIG_ENDIAN=t
.endif

